from .base_create_apiview import BaseCreateAPIView
from .base_delete_apiview import BaseDestroyAPIView
from .base_list_apiview import BaseListAPIView
from .base_retrieve_apiview import BaseRetrieveAPIView
from .base_update_apiview import BaseUpdateAPIView