# Generated by Django 2.0 on 2018-03-03 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deleted Time', null=True, verbose_name='DateTime Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier.', unique=True, verbose_name='Unique Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Keep this record active or not.', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Keep this record active or not.', verbose_name='Is Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation Date.', verbose_name='DateTime Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last Update.', verbose_name='DateTime Updated')),
                ('name', models.CharField(help_text='Category Name.', max_length=128, verbose_name='Category Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='User Who Created This Record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymodel_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User Who Last Updated This Record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymodel_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deleted Time', null=True, verbose_name='DateTime Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier.', unique=True, verbose_name='Unique Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Keep this record active or not.', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Keep this record active or not.', verbose_name='Is Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation Date.', verbose_name='DateTime Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last Update.', verbose_name='DateTime Updated')),
                ('title', models.CharField(blank=True, help_text='Title of the Post.', max_length=256, null=True, verbose_name='Post Title')),
                ('text', models.TextField(blank=True, help_text='Text of the Post.', null=True, verbose_name='Post Text')),
                ('category', models.ForeignKey(help_text='Select a Category Name.', on_delete=django.db.models.deletion.CASCADE, related_name='post_model_category', to='blog.CategoryModel', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, help_text='User Who Created This Record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postmodel_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User Who Last Updated This Record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postmodel_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'blog_posts',
            },
        ),
    ]
