# Generated by Django 2.0 on 2017-12-07 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 7, 20, 36, 57, 998959), help_text='Creation Date.', verbose_name='DateTime Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last Update.', verbose_name='DateTime Updated'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(blank=True, help_text='Category Name.', max_length=128, null=True, verbose_name='Category Name'),
        ),
    ]
