# Generated by Django 2.0 on 2018-03-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(blank=True, help_text='Category Name.', max_length=128, null=True, verbose_name='Category Name'),
        ),
    ]
