# Generated by Django 2.0 on 2018-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180305_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(help_text='Select a Category Name.', related_name='post_model_categories', to='blog.CategoryModel', verbose_name='Category'),
        ),
    ]
