# Generated by Django 2.0 on 2018-03-12 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20180312_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deleted Time', null=True, verbose_name='DateTime Deleted')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier.', unique=True, verbose_name='Unique Identifier')),
                ('is_active', models.BooleanField(default=True, help_text='Keep this record active or not.', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Keep this record active or not.', verbose_name='Is Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation Date.', verbose_name='DateTime Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last Update.', verbose_name='DateTime Updated')),
                ('name', models.CharField(blank=True, help_text='Tag Name.', max_length=128, null=True, verbose_name='Tag Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='User Who Created This Record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagmodel_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User Who Last Updated This Record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagmodel_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'blog_tags',
            },
        ),
    ]
