# Generated by Django 2.0 on 2018-03-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tagmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select Tags.', null=True, related_name='post_model_tag', to='blog.TagModel', verbose_name='Tags'),
        ),
    ]
