# Generated by Django 2.0 on 2018-03-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select Tags.', related_name='post_model_tag', to='blog.TagModel', verbose_name='Tags'),
        ),
    ]
